import type { Metadata } from "next";
import { Andada_Pro, Be_Vietnam_Pro, Cascadia_Mono } from "next/font/google";
import "./globals.css";
import { AppProvider } from "./AppProvider";

const lxgwWenKaiMonoTc = Cascadia_Mono({
  subsets: ["latin", "vietnamese"],
  variable: "--font-lxgwWenKaiMonoTc",
  weight: ["200", "300", "500"],
  adjustFontFallback: false,
});

const andadaPro = Andada_Pro({
  subsets: ["latin", "vietnamese"],
  variable: "--font-andada-pro",
});

const beVietnamPro = Be_Vietnam_Pro({
  subsets: ["latin", "vietnamese"],
  weight: ["300", "800"],
  variable: "--font-be-vietnam-pro",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${lxgwWenKaiMonoTc.variable} ${andadaPro.variable} ${beVietnamPro.variable} ${beVietnamPro.className} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col antialiased">
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
