import type { Metadata } from "next";
import { Andada_Pro, Cascadia_Mono, Inter } from "next/font/google";
import "./globals.css";
import { AppProvider } from "./AppProvider";

const cascadiaMono = Cascadia_Mono({
  subsets: ["latin", "vietnamese"],
  variable: "--font-cascadia-Mono",
  weight: ["200", "300", "500"],
  adjustFontFallback: false,
});

const andadaPro = Andada_Pro({
  subsets: ["latin", "vietnamese"],
  variable: "--font-andada-pro",
});

const inter = Inter({
  subsets: ["latin", "vietnamese"],
  weight: ["300", "400", "500", "700", "900"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${cascadiaMono.variable} ${andadaPro.variable} ${inter.variable} ${inter.className} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col antialiased">
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
