export const LifeDomains = {
  PHYSICAL: 'DOMAIN_364',
  RELATIONAL: 'DOMAIN_247',
  SPIRITUAL: 'DOMAIN_584',
  EMOTIONAL: 'DOMAIN_953',
  INTELLECTUAL: 'DOMAIN_424',
  ECOLOGICAL: 'DOMAIN_744',
  VOCATIONAL: 'DOMAIN_929',
} as const;
